# Generated by Django 5.1 on 2024-10-19 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CafeBooking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='place',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CafeBooking.office', verbose_name='Офис'),
        ),
        migrations.AlterField(
            model_name='place',
            name='short_name',
            field=models.CharField(max_length=5, verbose_name='Короткое название'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='cancel_reason',
            field=models.CharField(max_length=100, null=True, verbose_name='Причина отмены'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CafeBooking.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CafeBooking.time', verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CafeBooking.type', verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CafeBooking.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(max_length=25, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='time',
            name='time',
            field=models.CharField(max_length=15, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='type',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CafeBooking.place', verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(verbose_name='Заблокирован'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(max_length=20, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=20, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CafeBooking.role', verbose_name='Роль'),
        ),
    ]
