# Generated by Django 5.1 on 2024-10-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CafeBooking', '0003_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=20, unique=True, verbose_name='Логин'),
        ),
    ]
