# Generated by Django 5.1 on 2024-10-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CafeBooking', '0004_alter_user_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=20, verbose_name='Логин'),
        ),
    ]
