# Generated by Django 5.1 on 2024-11-12 07:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CafeBooking", "0006_reservation_is_archivated"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="creation_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
